### ISSUE TITLE
"Not supported" in when used in component

### ISSUE THREAD

**Issue by BabyDino** [ChrisEbert/strapi-plugin-country-select#2]
Hi!

![image](https://user-images.githubusercontent.com/4608702/209800267-8f7ad5b5-f5ff-41a9-8f1b-4d36cd133fa2.png)

When adding a country into a component I get "Not supported", when I add the field into a collection it works just fine.

This worked before, maybe something changed in Strapi? Any ideas?

**Comment by ChrisEbert** [comment]
Thank your for reporting, but I it's working for me with the latest version of Strapi. 

Could you please give me some more information about your setup?

- What version of Strapi you are using?
- Which interface language is selected for your user profile?
- Are there any console errors?

**Comment by BabyDino** [comment]
Disregard, my bad. I had to rebuild the admin and it works fine. Sorry for wasting your time. Happy new year :)
