### ISSUE TITLE
No validation server side -> be careful when using the API to add a country

### ISSUE THREAD

**Issue by philohelp** [ChrisEbert/strapi-plugin-country-select#3]
This can lead to very bad surprises. I added the component and sent a country name ("France") instead of its code ("FR"). That made the content manager crash for my content-type.

**Comment by ChrisEbert** [comment]
Thank you for reporting, I will fix it immediately.

**Comment by ChrisEbert** [comment]
Unfortunately strapi doesn't provide a way for server side validation of custom fields. But implementation is already under consideration: https://strapi.canny.io/developer-experience/p/validations
So if you really need some validation it has to be made on the controller level of your content-type.

For the moment I have fixed the crash of the content manager. Also an error is displayed for unsupported country codes.

**Comment by philohelp** [comment]
Cool enough, thanks
